---
title: "Semesteroppgave sok 1004"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r, include=FALSE}
load(url("https://bit.ly/2YBntjg"))

library(tidyverse)
library(gglorenz)
library(ineq)
```
## Oppgave A
```{r}
inntekt <- skattetall %>%
  arrange(inntekt)

inntekt %>% 
  ggplot(aes(inntekt)) +
  stat_lorenz(desc = FALSE) +
  coord_fixed() +
  geom_abline(linetype = "dashed") +
  theme_minimal() +
  labs(x = "Befolkning",
       y = "Inntekt",
       title= "Gini for inntekt i Troms (2015)") +
  annotate_ineq(inntekt$inntekt)

befolkning <- inntekt %>% 
  summarise(n=n())

tibble(
  "Fylke" = c("Troms"),
  "Gini" = ineq(inntekt$inntekt)*100,
  "inntekt" = mean(skattetall$inntekt),
  "Befolkning" = c(befolkning$n)
)
```
Vi ser på grafen for gini indeksen over inntekt i Troms fylke fra 2015, at den var på 0.45. Vi kan se at kurven begynner helt flat på grunn av at flere av observasjonene mangler inntekt. Mange av disse er i aldersgruppen 0-20, hvor de fleste i denne alderen ikke er i jobb.
## Oppgave B
```{r}
skattetall1 <- skattetall %>% 
  mutate(kommune=kommnr)

skattetall1 <- skattetall1 %>% 
  mutate(kommune=recode(kommune,
                        "1902" = "Tromsø",
                        "1903" = "Harstad",
                        ))
skattetall1[is.na(skattetall1)] <- "Omegn"
gini.kommune <- skattetall1 %>% 
  group_by(kommune) %>% 
  summarise(gini=ineq(inntekt))
inntekt <- skattetall1 %>% 
  group_by(kommune) %>% 
  summarise(mean(inntekt))
befolkning <- skattetall1 %>% 
  group_by(kommune) %>% 
  summarise(n=n())
pros_bef <- skattetall1 %>% 
  group_by(kommune) %>% 
  summarise( percent = 100*n()/nrow(skattetall1))

tibble(
  "kommune" = c("Harstad", "Omegn", "Tromsø"),
  "Gini (%)" = c(gini.kommune$gini)*100,
  "Inntekt" = c(inntekt$`mean(inntekt)`),
  "Personer" = c(befolkning$n),
  "Andel (%)" = c(pros_bef$percent))
```

## Oppgave C
```{r}
skattetall1 <- skattetall1 %>% 
  mutate(disponibel_inntekt=inntekt-skatt) 
skattetall1[skattetall1 < 0] <- 0

disponibel_inntekt <- skattetall1 %>% 
  arrange(disponibel_inntekt)

disponibel_inntekt %>% 
  ggplot(aes(disponibel_inntekt)) +
  stat_lorenz(desc = FALSE) +
  coord_fixed() +
  geom_abline(linetype = "dashed") +
  theme_minimal() +
  labs(x = "Befolkning",
       y = "Disponibel inntekt",
       title= "Gini for inntekt i Troms (2015)") +
  annotate_ineq(disponibel_inntekt$disponibel_inntekt)
```

## Oppgave D
```{r}
inntekt <- skattetall %>%
  arrange(inntekt)

inntekt %>% 
  ggplot(aes(x=skatt, y=inntekt)) +
  geom_point(aes(y=inntekt), color="dark red") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(labels = scales::comma) +
  labs(title="Inntekt og Skatt",
       x="Skatt",
       y="Inntekt") +
  theme_bw()
```
## Oppgave E
```{r}
Formue <- skattetall %>%
  arrange(formue)

Formue %>% 
  ggplot(aes(x=skatt, y=formue)) +
  geom_point(aes(y=formue), color="dark red") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(labels = scales::comma) +
  labs(title="Inntekt og Formue",
       x="Skatt",
       y="Formue") +
  theme_bw()
```
## Oppgave F
```{r}
tromso <- skattetall %>%
  filter(kommnr==1902)
harstad <- skattetall %>% 
  filter(kommnr==1903)
omegn <- skattetall %>% 
  filter(kommnr>=1904)

for_omegn <- mean(omegn$formue)
for_tromso <- mean(tromso$formue)
for_harstad <- mean(harstad$formue)
for_troms <- mean(skattetall$formue)

gini_for_omegn <- ineq(omegn$formue)
gini_for_tromso <- ineq(tromso$formue)
gini_for_harstad <- ineq(harstad$formue)
gini_for_troms <- ineq(skattetall$formue)
per_omegn <- omegn %>% 
  summarise(n=n())
per_tromso <- tromso %>% 
  summarise(n=n())
per_harstad <- harstad %>% 
  summarise(n=n())
pros_bef <- skattetall1 %>% 
  group_by(kommune) %>% 
  summarise(percent = 100*n()/nrow(skattetall1))
personer <- skattetall1 %>% 
  summarise(n=n())
pros_total <- personer %>% 
  group_by(n) %>% 
  summarise(percent = 100*n()/nrow(personer))
tibble(
  "kommune" = c("Harstad","Omegn", "Tromsø", "Troms"),
  "Gini (%)" = c(gini_for_harstad*100, gini_for_omegn*100, gini_for_tromso*100, gini_for_troms*100),
  "Formue" = c(for_harstad, for_omegn, for_tromso, for_troms),
  "Personer" = c(per_harstad$n, per_omegn$n, per_tromso$n, personer$n),
  "Andel (%)" = c(pros_bef$percent, pros_total$percent))
```


## Oppgave G
```{r}
aldersgruppe <- skattetall %>% 
  group_by(aldersgruppe) %>% 
  summarise(gini_aldersgruppe=ineq(inntekt))

aldersgruppe %>% 
  ggplot(aes(x=aldersgruppe, y=gini_aldersgruppe)) +
  geom_point(size=3, color="dark red") + 
  geom_segment(aes(x=aldersgruppe, xend=aldersgruppe, y=0, yend=gini_aldersgruppe)) +
  labs(title="Inntekt og Formue",
       x="Aldersgruppe",
       y="Gini") +
  theme_bw()
```
## Oppgave H
```{r}
Menn <- skattetall %>%
  filter(kjonn=="M")
Kvinner <- skattetall %>% 
  filter(kjonn=="F")

aldersgruppe_menn <- Menn %>% 
  group_by(aldersgruppe) %>% 
  summarise(gini_aldersgruppe=ineq(inntekt))
aldersgruppe_kvinner <- Kvinner %>% 
  group_by(aldersgruppe) %>% 
  summarise(gini_aldersgruppe=ineq(inntekt))


ggplot(NULL, aes(x= aldersgruppe, y=gini_aldersgruppe)) + 
  geom_bar(data=aldersgruppe_menn, aes(color='Menn'), stat = "identity",
           width=.4, position=position_nudge(x = -0.2)) +
  geom_bar(data=aldersgruppe_kvinner, aes(color='Kvinner'), stat = "identity", 
           width=.4, position=position_nudge(x = 0.2)) +
  labs(title="Gini & Aldersgruppe",
       x="Aldersgruppe",
       y="Gini")
```

